version: '2'

services:
    # Laravel application
    laravel_php_fpm:
        build: 
            context: ./docker
            dockerfile: "Dockerfile.phpfpm"
        container_name: laravel-phpfpm
        volumes:
            - ./docker/laravel:/var/www/laravel
        links:
            - laravel_database
        ports:
            - 9010:9000
        depends_on:
            - laravel_database
        environment:
            - DB_PORT=3306
            - DB_HOST=laravel_database

    # Webserver
    nginx:
        build: 
            context: ./docker
            dockerfile: Dockerfile.nginx
        container_name: laravel-nginx
        ports:
            - "84:80"
        links:
            - laravel_php_fpm
        volumes_from:
            - laravel_php_fpm
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx
        restart: always

    # The Database
    laravel_database:
        image: mariadb:10.2
        container_name: laravel-mysql
        volumes:
            - "./docker/db:/docker-entrypoint-initdb.d"
            - "./docker/db/dbdata:/var/lib/mysql"
        environment:
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=root"
        ports:
            - "33073:3306"
        restart: always
